# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from detection_only/Bbox6Array.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import detection_only.msg

class Bbox6Array(genpy.Message):
  _md5sum = "61b8f2a52aff12e25f2957c1314c78d3"
  _type = "detection_only/Bbox6Array"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# bboxes 
# [x1,y1,x2,y2,conf,class]
Bbox_6[] bboxes 
================================================================================
MSG: detection_only/Bbox_6
# 1 bbox 
# [x1,y1,x2,y2,conf,class]
# float32[] bbox_info
float32 x1
float32 y1
float32 x2
float32 y2
float32 conf
float32 cls"""
  __slots__ = ['bboxes']
  _slot_types = ['detection_only/Bbox_6[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bboxes

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Bbox6Array, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.bboxes is None:
        self.bboxes = []
    else:
      self.bboxes = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.bboxes)
      buff.write(_struct_I.pack(length))
      for val1 in self.bboxes:
        _x = val1
        buff.write(_get_struct_6f().pack(_x.x1, _x.y1, _x.x2, _x.y2, _x.conf, _x.cls))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.bboxes is None:
        self.bboxes = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.bboxes = []
      for i in range(0, length):
        val1 = detection_only.msg.Bbox_6()
        _x = val1
        start = end
        end += 24
        (_x.x1, _x.y1, _x.x2, _x.y2, _x.conf, _x.cls,) = _get_struct_6f().unpack(str[start:end])
        self.bboxes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.bboxes)
      buff.write(_struct_I.pack(length))
      for val1 in self.bboxes:
        _x = val1
        buff.write(_get_struct_6f().pack(_x.x1, _x.y1, _x.x2, _x.y2, _x.conf, _x.cls))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.bboxes is None:
        self.bboxes = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.bboxes = []
      for i in range(0, length):
        val1 = detection_only.msg.Bbox_6()
        _x = val1
        start = end
        end += 24
        (_x.x1, _x.y1, _x.x2, _x.y2, _x.conf, _x.cls,) = _get_struct_6f().unpack(str[start:end])
        self.bboxes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
